### ISSUE TITLE
Thousands of XMLSERVICE jobs

### ISSUE THREAD

**Issue by kadler** [IBM/xmlservice#13]
**[Original report](https://bitbucket.org/inext/xmlservice-rpg/issue/13) by Don (Bitbucket: [msddcb](https://bitbucket.org/msddcb), GitHub: Unknown).**

----------------------------------------

I am trying to control the number of XMLSERVICE jobs running on IBMi at V7R3.

I have this issue both where Zend server is running on IBMi and where Zend server is on a remote Linux box and using ODBC to connect to IBMi.

Recently we had over 13000 XMLSERVICE jobs running.  Ending the sub-system and restarting is the only way we are currently managing but I am hoping there is a setting that will allow the number of jobs to be controlled.

Thanks you for any suggestions

**Comment by jimoibm** [comment]
I think previous answer from Jesse  is right. To use IPC against stateless for performance consideration, user needs to specified IPC key path and control flag *SBMJOB. Also with control flag *IDLE(n) will set timer to send SIGTERM to kill the server job. For plugconf file, the default for n is 0, then then server job keeps waiting on IPC semaphore. 
From the code comments and wiki source, looks like there should be custom hooks in plugconfX file, X=1, 2, 3...q. There should be default kill time set in those other than q. This seems another way to configure. 
**From the current information, I can not see a BUG from this reported issue.** 
@kadler  I could not found the original source in BitBucket, but looks like the GitHub we don't have those plugconfX anymore. Maybe we need them back.

**Comment by kadler** [comment]
@jimoibm If the user wants to build a custom version of XMLSERVICE, they can modify the code directly. There's no reason to have multiple versions of the same file laying around. Additionally, if enough people want to configure this differently, we could make it configurable by the `configure` script, just as the debug level and library are today.

I'm not convinced a compile-time configuration option is the right way here anyway, since the caller of XMLSERVICE can always set the timeout value explicitly with the `*IDLE()` ctl option. This is much more flexible than changing the compile-time option, since it can be tuned per-application and doesn't require re-compiling XMLSERVICE to adjust.

The only benefit I could see in changing XMLSERVICE would be to set a better default behavior:

1. change to a more sane default (what is _sane_, though? 1 minute? 10 minutes? 1 hour?)
2. force the user calling XMLSERVICE to pass a timeout value and error if it's not set

Personally, I think option 2 is better, but either way that's a behavior change and that's not gonna happen.

**Comment by jimoibm** [comment]
@kadler Thanks for your thoughts! I agree. Since the timeout is configurable, let's keep what we have now. 
Since the wiki have info about the time relevant introduction, we may need to drop those to align with current code. I saw you have a task created for documentation I will work on that.
