### ISSUE TITLE
Output Not Escaped

### ISSUE THREAD

**Issue by kadler** [IBM/xmlservice#15]
**[Original report](https://bitbucket.org/inext/xmlservice-rpg/issue/15) by Danny Roessner (Bitbucket: [droessner](https://bitbucket.org/droessner), GitHub: [danny-hcs](https://github.com/danny-hcs)).**

----------------------------------------

I have this test RPG program:
```
#!rpg
**free

dcl-pi *N;
  output char(10);
end-pi;

output = '&<>"''';

return;         
```

I use XMLSERVICE to call the program:
```
#!SQL

call QXMLSERV.iPLUG4K(
    'NA',
    '*here',
    '<pgm name="ESCAPETEST" lib="DROESSNER" error="on"><parm io="out"><data name="OUTPUT" type="10a"></data></parm></pgm>',
    'NULL'
);
```

The output is:
```
#!XML
<pgm name="ESCAPETEST" lib="DROESSNER" error="on">
  <parm io="out">
    <data name="OUTPUT" type="10a">&<>"'</data>
  </parm>
  <success><![CDATA[+++ success DROESSNER ESCAPETEST ]]></success>
</pgm>
```

None of the special XML characters are being escaped.

**Comment by bjeromeHCS** [comment]
@kadler Was this change put into 2.0.1 or is there a newer version? We re-installed 2.0.1 from the .zip available on the youngiprofessionals.com but it seems the output is not escaping these characters again even with the *escp flag.

**Comment by kadler** [comment]
This change was made after 2.0.1, so it wouldn't be in there and we have yet to release a version since then. You can either download the [zip](https://github.com/IBM/xmlservice/archive/9ad9ebf50b865de790034efd44a0305280a65035.zip) from that release or the latest from the master branch.

**Comment by bjeromeHCS** [comment]
Okay thanks. We'll work on switching our scripts to use the git repo instead.
