### ISSUE TITLE
Calling XMLSERVICE from a 64-bit PASE job fails

### ISSUE THREAD

**Issue by kadler** [IBM/xmlservice#17]
**[Original report](https://bitbucket.org/inext/xmlservice-rpg/issue/17) by me.**

----------------------------------------

When calling XMLSERVICE from within a 64-bit PASE job, the result is failure. The return coe is 0, but no output is returned. This is due to assumptions throughout the code that assume that a PASE pointer is 32-bits.

This causes the iLibCall transport to fail on 64-bit Python versions: https://github.com/IBM/python-itoolkit/issues/17

**Comment by jimoibm** [comment]
@kadler Looks like iLibCall calls QXMLSERV.XMLSTOREDP on exported procedure runascii, but I set a breakpoint there and didn't see xmlservice was called.  Then I removed QXMLSERV library. I still got the same error as you posted. Anything wrong with my environment or the error was not in xmlservice? Thanks!

**Comment by kadler** [comment]
I think you need to build the latest master branch code, since the iLibCall C code had 64-bit bugs as well.

**Comment by jimoibm** [comment]
@kadler Thanks! I changed to use 64-bit variables/parms on the code path for the iToolKit test case and it is workable now. But there are  bunches of similar situations to fix in plugpase.rpgle. 
Need your help on the following questions:
1) For PASE shell jobs, always use 64-bit mode?
2) For Db2 calls, guess they uses 32-bit mode? I saw iDB2Call now fails on my fix using 64-bit mode.
3) Do we need to check 64-bit on runtime and then determine how to call PASE APIs?

**Comment by kadler** [comment]
>     1. For PASE shell jobs, always use 64-bit mode?

We can check [Qp2ptrsize](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/apis/qp2ptrsize.htm) to see what PASE bitness we are and act accordingly. The only tricky bit is when PASE hasn't yet started (ie. `Qp2ptrsize` returns 0). In that case, I think we default to 32-bit as it has in the past. We can think about some option to enable 64-bit support.

>     2. For Db2 calls, guess they uses 32-bit mode? I saw iDB2Call now fails on my fix using 64-bit mode.

It shouldn't be affected by it. Sounds like there's a bug in your changes.

>     3. Do we need to check 64-bit on runtime and then determine how to call PASE APIs?

Yes. This will affect how we load and run PASE commands and certain sizes will change on Qp2 APIs due to 64-bit.

**Comment by jimoibm** [comment]
Thanks @kadler ! qp2ptrSize works well to help determine 32bit or 64bit in runtime. We have StartPase32 procedure and I put qp2ptrSize after pase is started. It should be OK to avoid situation of pase not active. Now I tested this iToolkit test case, iLibCall goes 64bit and iDB2Call goes 32bit. I will make the similar changes to all the other procedures.

**Comment by jimoibm** [comment]
@kadler Is the code OK to merge into the master? Not sure if my last changes cause any problems with the whitespace drop.

**Comment by jimobit** [comment]
@kadler this has been merged. Please have this closed. Thanks!

**Comment by Wikus86** [comment]
Hi, 
do we need to compile the xmlservice-cli into '/QOpenSys/pkgs/bin' ?

I am having an issue where xml-service opens pase in 32bit, causing my jvm not to start as it is 64bit...

**Comment by kadler** [comment]
It depends on how you are using it. If you're using nodejs-itoolkit or python-itoolkit, they hardcode the path: https://github.com/IBM/nodejs-itoolkit/blob/404ab68ee32c9af7ec43210b588e7b2df17fcbee/lib/transports/sshTransport.js#L42 https://github.com/IBM/python-itoolkit/blob/d2ec84d71a2192ec0e2c244fe580753e03b90dd1/src/itoolkit/transport/ssh.py#L78 Other callers, I'm not sure.

**Comment by richardschoen** [comment]
Are you trying to call a Java app via XMLService ?

**Comment by Wikus86** [comment]
No, calling an rpg program that calls an email sending program that uses Java. Hope that makes sense

**Comment by richardschoen** [comment]
It does. When using XMLSERVICE you should probably not be placing direct calls to a Java app. Too many odd call layers happening there.  Perhaps you could submit the call to the email send program possibly.  If your RPG has embedded Java it complicates the call stack even further,

**Comment by richardschoen** [comment]
You could also change your RPG to call the 32bit JVM instead of 64-bit.  But not sure how much that would help the situation. 

Either way embedding Java in RPG is fraught with pain.    

You could possibly refactor your Java piece to be a standalone class. 

Without seeing the code it's really hard to tell.

**Comment by Wikus86** [comment]
I tried setting it to 32bit but got other issues.

My problem is that i am just calling the legacy programs from nodejs and would rather not have to change the programs.

But I hear what you are saying,  might just have to go through the exercise and refactor the programs.

**Comment by richardschoen** [comment]
If you wrap the RPG call into a SBMJOB command you can submit the RPG call as a regular job so it separates from the XMLSERVICE call and goes off to do its own thing.

Instead of: CALL RPGPGM

Do this: SBMJOB  CMD(CALL RPGPGM)

Only thing you don't get back is the success or fail right away.

Good luck

**Comment by richardschoen** [comment]
One other thought I just had is: Does your RPG program run in its own activation group ?  Possibly having it create its own activation group could help. 

Just a little end of day thought process for not re-engineering.

**Comment by Wikus86** [comment]
> One other thought I just had is: Does your RPG program run in its own activation group ? Possibly having it create its own activation group could help.
> 
> Just a little end of day thought process for not re-engineering.

On this specific program I am calling a service program from nodejs so the activation group is *caller, dont think you can change that.


I created a test program that calls the same email program and created its own activation group, but same result.

Calling program
H DEBUG DATEDIT(*YMD)             
H Option(*SrcStmt:*NoDebugIO)     
H bndDir('S_MAIN_B')              
H DFTACTGRP(*NO) ActGrp('TST')    
H pgminfo(*pcml:*module:*dclcase) 



Procedure in the mail program where it crashes. As soon as it calls makeString, it starts the java environment and then crashes.
 D makestring      PR              O    EXTPROC(*JAVA:      
 D                                       'java.lang.String':
 D                                       *CONSTRUCTOR)      
 D    bytes                     256A    CONST VARYING       


I tried submitting the mailing program and that seems to work.

Is there not a way to compile the xmlservice-cli in 64bit? Just thinking about it more and we have other programs that uses XSSF to generate Excel reports and that also uses java. So not going to be viable to change all programs to use java to be submitted.

**Comment by richardschoen** [comment]
You can switch the JVM you use by simply pointing JAVA_HOME to the right directory.  Have you tried the 32-bit JVM ?

I also believe you can compile xmlservice-cli in 64 bit mode with these env variables in your job:
```
OBJECT_MODE=64     
export OBJECT_MODE 
```

**Comment by Wikus86** [comment]
I have tried the 32bit but got other errors. Will try again and let you know.

Can you perhaps provide me with the command to compile the xmlservice-cli?

**Comment by richardschoen** [comment]
I think you just clone the repo, export the env variables, change into the dir and run make. 

Been a couple years.
