### ISSUE TITLE
ftpcompile.sh missed from migration

### ISSUE THREAD

**Issue by jimoibm** [IBM/xmlservice#29]
@kadler I didn't find the ftpcompile.sh in GitHub which was in the first level directory in BitBucket. That script is used to push a build from linux to i and building PTF process also needs it.

**Comment by jimoibm** [comment]
looks like crt* files are all missing.

**Comment by kadler** [comment]
Yes, that is by design.

Everything should be built on IBM i with:

```sh
./configure --library mylib
make
```

**Comment by jimoibm** [comment]
@kadler I tried the new build way. It is pretty good!
Some chars in the xmlservice output of xml seems different with ccsid 37 job.  ! [ ] are not displayed correctly.  Used cpyf Toccsid(37) to convert but seems not right. 

`<success><|¢CDATA¢+++ success JIMOXML XMLTEST !!></success>`

**Comment by jimoibm** [comment]
Run system "chgjob ccsid(37)" with cpyf Toccsid(37), ! [ ] were displayed correctly.

**Comment by jimoibm** [comment]
Close this and will handle the ccsid issue in the other issue #32
