### ISSUE TITLE
DATA tags in output have wrong converted chars after migrated to new build environment

### ISSUE THREAD

**Issue by jimoibm** [IBM/xmlservice#32]
In new compile environment, RPG source files stay in ccsid 819. CRTRPGMOD from IFS sources files could not specify conversion to job ccsid. The best way may be change the xmlservice code to be independent with source file ccsid. Use hexidecimal to initialize the Unicode constants for DATA tag.

**Comment by jimoibm** [comment]
@kadler I have DATA tag ccsid fixed. It's easy just a few lines of code. But when I look further, I see there are more char like '|' which has different ccsids between 819 and 37. I didn't find any parms to indicate CRTRPGMOD to convert IFS source file ccsid to job ccsid(37). So I am thinking one of the following options:
1. fix all the '|' alike chars with ccsid issues but the changes are not small.. many spots to check
2. change the build tool. maybe give extra parms to copy rpg sources files to ccsid 37 into a temp directory before make
I am appreciate if there are better ideas. Thanks!

**Comment by jimoibm** [comment]
reminder for myself... DATA tag changes in src/plugxml.rpgle

**Comment by jimoibm** [comment]
@kadler I made changes to 819 chars that I am aware of in the code. then we can leave the build script as is. Could you approve my PR for 64-bit? My current changes are based on some files in that PR. Thanks!

**Comment by kadler** [comment]
> more char like '|' which has different ccsids between 819 and 37

That's an understatement! 819 is an ASCII CCSID, while 37 is EBCDIC. I think the bigger issue is that '|' has different values between 37 and other EBCDIC CCSIDs (it's the same across all ASCII CCSIDs).

My guess is that the only way to make it really make it work (as XMLSERVICE works today) is to do a conversion to job CCSID for those replacement characters. Ideally, the XML would always be received in UTF-8 and generated in UTF-8. Using the stored procedures as convenient conversion to/from job ccsid for the general case just results in too many unfixable corner cases.

**Comment by jimoibm** [comment]
@kadler You are right that it is an issue crossing different CCSID's. To isolate with source file CCSID, I changed those chars that I am aware of to be UTF-16 coded for the constant variables and then covert to job ccsid chars in runtime to avoid the source CCSID issue for CRTRPDMOD.But there may be other chars missing for the fix.  
Using UTF-8 as in and out is ideal, but I am worried both users' program and xmlservice need to be changed.
How about the other option.. change the compile script, first copy the 819 source files to /tmp and then change job ccsid to 37 and then make.. at last change ccsid back to origin ccsid(the default pase ccsid is changed to 1208 in 7.4). In current code, besides 819 issue, I noticed there were assumptions... think of the job ccsid is 37 when creating modules for some assignments of constant variables.

**Comment by kadler** [comment]
Yes, converting to UTF-8 is a much bigger issue and would require quite a big change. I think it's something that needs to be done at some point though.

**Comment by jimoibm** [comment]
@kadler My current changes that hardcode constants with UTF-16 won't hurt our future decision but as a temporary solution to make the xmlservice work. If you agree with that, I will submit a PR for review.

**Comment by kadler** [comment]
Closed by #36
