### ISSUE TITLE
XMLSTOREDP service program not exporting RUNASCII

### ISSUE THREAD

**Issue by kadler** [IBM/xmlservice#37]
With #33, XMLSTOREDP is only exporting functions defined in the export source. In #27, I said we needed to only export the iPlug* functions, since the XMLSTOREDP service program is ostensibly there to support the stored procedures. 

I forgot about RUNASCII and other functions that were used by both the Python toolkit iLibCall and the xmlservice-cli utility. Ideally these utilities would use RUNASCII from a dedicated service program instead of XMLSTOREDP, but we don't have one of those *and* they are already using it so we need to keep that behavior.

**Comment by jimoibm** [comment]
I will look at the code to see which ones should be added back.
