### ISSUE TITLE
How to use pure xml to call PGM/CMDwith Chinese Chars (937)?

### ISSUE THREAD

**Issue by owen-rpx** [IBM/xmlservice#52]
My web page will input Chinese chars like '測試'

My nodejs will send xml str to XmlService with Post method and the form body like below:
`<?xml version="1.0"?>
<xmlservice>
<cmd>CHGLIBL LIBL(QGPL QTEMP)</cmd>
<pgm name='PGMNAME' lib=''>
	<parm io='both'><data type='32a'>63jo3fzykm0wo0s408w04kw44</data></parm>
	<parm io='both'><data type='10a'>USR</data></parm>
	<parm io='both'><data type='10a'>Test</data></parm>
	<parm io='both'><data type='10a'></data></parm>
	<parm io='both'><data type='50a'>測試</data></parm>
	<parm io='out'><data type='1024a'  var='$out' ></data></parm>
</pgm>
</xmlservice>`

The cmd string:
`<?xml version="1.0"?>
<xmlservice>
<cmd>CHGLIBL LIBL(LIBNAME QGPL       QTEMP)</cmd>
<cmd exec='rexx'>CMD1 SSNID(7kr4yyvy0dk4o8k884k8wkccg) USR(USE) PAE(''A004'')TSKTXT(''測試'')  RTNMSG(?) 
</cmd>
</xmlservice>`

**PS: HTTPAdmin already config the CCSSID with 937/950**

Could give us the example how to deal with them? thanks.

@jimoibm
@kadler

**Comment by jimoibm** [comment]
Can you please show me more details on what the result/error was? Was the URI chars were escaped in the browser? Was the job calling XMLService in the job ccsid as you expected? What ccids was your cmd/pgm expecting for chars encoded with?

**Comment by owen-rpx** [comment]
Below is cmd results:

`<?xml version="1.0"?>
<xmlservice>
<cmd><success><![CDATA[+++ success CHGLIBL LIBL(QGPL  QTEMP)]]></success>
</cmd>
<cmd exec='rexx'><success><![CDATA[+++ success CMD1 SSNID(1i6cvqpz0ce84ws040gc8wsg4) USR(USE) PAE(''A002'')   RTNMSG(?) TSKTXT(''皜祈岫'')]]></success>
<row>
<data desc='RTNMSG'><![CDATA[ Task A002 already exists.  Cannot add.]]></data>
</row>
</cmd>
</xmlservice>`

**Comment by jimoibm** [comment]
Are you saying it is working now?

- If yes, is anything else expected from us to look at? are you indicating errrors in nodejs?
- If no, 
> Did you use HTTP server or nodejs? 
> Looks like CMD1 is a placeholder for your own object? Did you check the ccsid/encoding from there?

**Comment by owen-rpx** [comment]
Not working, 
I use Postman to debug it and Post method url is http://xxx.xxxx.com:portNum/cgi-bin/xmlcgi.pgm
The CMD1 is placeholder, yes. 
I try to encoding using Big5 and use hex='on' as below:
`<?xml version="1.0"?>
<xmlservice>
<cmd>CHGLIBL LIBL(ACMSALIB QGPL  QTEMP)</cmd>
<cmd exec='rexx' hex='on' before='937/37'>CMD1 SSNID(1i6cvqpz0ce84ws040gc8wsg4) USR(XUDONGZ) PAE(''A002'') RTNMSG(?) TSKTXT(''測試'')</cmd>
</xmlservice>`

**Comment by jimoibm** [comment]
**hex='on'** means you need to give hexadecimal....  
**before/after='fromCCSID/toCCSID'** you need consider well on your job ccsid/parm ccsid pgm taking in

if using command call, you need to HEX'd all the command string..
You may consider using pgm call for better control of ccsid conversion on the only needed parms

If hit error complaining **Argument list too long.**, it  is caused by a bug below  if receiver needs to be bigger than input for iconv(). Try using hex without conversion and workaround in your code..
```
size = anyBIG(index).bigsize; <-- should be bigger for receiver

rc = iconv(conv.conv
          :%addr(fromPtr):%addr(fromBytes)
          :%addr(toPtr):%addr(toBytes));  <-- toBytes should greater than fromBytes
```

Possible one spot change:
```
     P cacAddBig       B                   export
     D cacAddBig       PI            10i 0
     D  bsize                        10i 0 value
     D  btype                         1A   value
     ...
       /free
         bsize = bsize * 4;  <--- make a bigger receiver size...
     ....

```
**Command call example:**
> ...&ipc=*NA&ctl="*here"&xmlin="<?xml version='1.0'?><cmd hex='on' before='1208/935' after='935/1208'>4348474C4942204C4942284A494D4F434E2920544558542827E4B8AD2729202020202020202020</cmd>"&xmlout=500000
> CHGLIB LIB(JIMOCN) TEXT('中')
> 935 -> 1208                                                             
> hex ->  IN: C3C8C7D3C9C240D3C9C24DD1C9D4D6C3D55D40E3C5E7E34D7D0E5BCF0F7D5D404040404040404040                                        
> hex -> OUT: 4348474C4942204C4942284A494D4F434E2920544558542827E4B8AD2729202020202020202020                            

**Result:**
```
<?xml version='1.0'?><cmd hex='on' before='1208/935' after='935/1208'><success>+++ success CHGLIB LIB(JIMOCN) TEXT('$õ')</success>
</cmd>
```
