### ISSUE TITLE
Qp0sDisableSignals ???

### ISSUE THREAD

**Issue by AndreaRibuoli** [IBM/xmlservice#60]
What's the point of mapping **Qp0sDisableSignals** to **Qp0sEnableSignals** ?

``` RPGLE
      *++++++++++++++++++++++++++++++++++++++++++++++++++++++++
      * Qp0sDisableSignals(): Disable signals
      *++++++++++++++++++++++++++++++++++++++++++++++++++++++++
     D Qp0sDisableSignals...
     D                 PR            10I 0 extproc('Qp0sEnableSignals')
```

**Comment by jimoibm** [comment]
It might be a copy/paste error to Qp0sDisableSignals. 
The export procedure is not used in components of XmlService internally. Should not cause any error yet. 
What is you usage of that?

**Comment by jimoibm** [comment]
Indeed there are export procedures not used internally. Not sure why they were added.

**Comment by alanseiden** [comment]
Created PR https://github.com/IBM/xmlservice/pull/61

**Comment by alanseiden** [comment]
PR has been merged.
